// <auto-generated />
namespace U5_W4_BuildWeek.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AggiuntoRicoveroAttivo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AggiuntoRicoveroAttivo));
        
        string IMigrationMetadata.Id
        {
            get { return "202310190904133_AggiuntoRicoveroAttivo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
